### ISSUE TITLE
Add Metadata to onClose & onSuccess

### ISSUE THREAD

**Issue by tristan-mono** [withmono/connect.js#18]
**Context**

The current callback functions in the instantiation of MonoConnect do not provide any feedback to the user.

**Problem**

Developers need better insight into the widget's state.

**Solution**

We should add a metadata object to onClose, onSuccess provide some greater insight into the widget. This will require updates to https://connect.withmono.com/ as will need to publish more information in the 'message' event.

onSuccess
- Code
- Metadata

onClose
- Error
- Metadata

**Comment by umar-abdullahi** [comment]
What metadata are you suggesting we should pass? @tristan-mono

**Comment by tristan-mono** [comment]
@umar-abdullahi I'm open to recommendations here's what I have in mind.

onSuccess Metadata
- `Institution` as an object or name. This can be used to customize a loading view while waiting to get transaction data.

onClose Metadata
- `Institution` as an object or name. This can be used to customize a loading view or a failed to connect view.
- `Status` as a string. This can be used to determine where the user exited the widget, maybe more of a nice to have for analytics etc.

**Comment by umar-abdullahi** [comment]
not sure we would support metadata for `onSuccess` just yet, but we can add a `viewName` property in metadata for `onClose`, this would indicate the view which a user dropped off
