### ISSUE TITLE
@mono.co/connect.js crashes Nextjs app

### ISSUE THREAD

**Issue by CRIMSON-CORP** [withmono/connect.js#43]
### Summary
App crashes when monoInstance.setup() is called
For bug reports, include detailed steps to reproduce or a minimal reproduction of the issue

### Other information
This is due to document not defined in Nodejs Server in Nextjs, please make this compatible with Nexjs

visual issues

Is this specific to one device, or does it happen on multiple devices?
![Screenshot 2022-10-19 154752](https://user-images.githubusercontent.com/71358573/196732693-01768fd2-b86d-46f9-b4e5-f1035eb08e70.png)
![Screenshot 2022-10-19 154848](https://user-images.githubusercontent.com/71358573/196732702-1ed0614d-e758-4bef-abc3-93c9ec9bbfe6.png)

##### My current solution
By checking if youre on the server on the client, one can stop the app from crashing

![Screenshot 2022-10-19 161916](https://user-images.githubusercontent.com/71358573/196733926-6efdc53a-562e-48b6-908a-7c5398eaa7c4.png)

**Comment by umar-abdullahi** [comment]
this is a known issue on isomorphic codebase, please refer to our nextjs implementation here https://github.com/withmono/connect.js/blob/develop/docs/examples/nextjs.md @CRIMSON-CORP
